name: Jeanine
author: Jeanine
url: "https://jeaninezpp.github.io"
baseurl: 
resume_site: 
description: Salt is for self-discipline, sweet for others.
github_username: Jeaninezpp
github: https://github.com/Jeaninezpp
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
include:
  - _pages
comments :
  gitalk :
    clientID : 
    clientSecret : 
    repo : 
    owner : 
    admin : 
    
# Google Analytics
# google_analytics: G-HC9BLYFY4T

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
